# fly.toml app configuration file for arpg-timeline-discord-bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arpg-timeline-discord-bot'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[env]
  DB_PATH = '/data/database.db'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
